<template lang="html">
<section class="wallet">
    <h2> {{ $t("wallet.title")}}: {{totalAmount}}</h2>
    <b-card-group columns>
        <b-card v-for="account in accounts" :key="account.id" bg-variant="secondary" text-variant="white" class="text-center">
            <b-card-header>
                <span>{{account.name}}
                    <IconCrypto :coinname="account.currency" color="color" format="svg" /></span>
            </b-card-header>
            <b-card-body>
                <b-card-text v-if="account.type == 'wallet'">{{account.balance.amount}} {{account.balance.currency}}</b-card-text>
                <b-card-text>{{account.native_balance.amount}} {{account.native_balance.currency}}</b-card-text>
            </b-card-body>
            <!-- <b-card-text>{{account}}</b-card-text> -->
            <b-button variant="light">Button</b-button>
        </b-card>

    </b-card-group>
</section>
</template>

<script lang="js">
import axios from './service/CoinbaseConfig.js';

export default {
    name: 'wallet',
    components: {},
    props: [],
    mounted() {
        this.getAxiosData();
    },
    data() {
        return {
            accounts: null,
            totalAmount: 0,
        }
    },
    methods: {
        /**
         * The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret
         * key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
         *  The timestamp value is the same as the CB-ACCESS-TIMESTAMP header.
         */
        getAxiosData() {
            axios
                .get('/v2/accounts')
                .then((response) => {
                    var rawAccounts = response.data.data;
                    this.accounts = rawAccounts.filter(account => account.balance.amount != 0)
                    this.totalAmount = this.accounts.reduce((total, x) => {
                        console.log(x);
                        return total + new Number(x.native_balance.amount);
                    }, 0);

                    this.totalAmount = Math.floor(this.totalAmount * 100) / 100;

                }).catch((err) => {
                    this.$emit('errorMsg', err)
                });
        }
    },
    computed: {

    }
}
</script>

<style lang="scss" scoped>
.wallet {}
</style>
