<template lang="html">
<section class="wallet">
    <h2> {{ $t("wallet.title")}}</h2>

    <b-card-group columns>

        <b-card v-for="account in accounts" :key="account.id" bg-variant="secondary" text-variant="white" :header="account.name" class="text-center">
            <b-card-text> {{account.balance.amount}}</b-card-text>
            <b-card-text>{{account}}</b-card-text>
            <b-button variant="light">Button</b-button>
        </b-card>

    </b-card-group>
</section>
</template>

<script lang="js">
import axios from 'axios';
import crypto from 'crypto';

export default {
    name: 'wallet',
    props: [],
    mounted() {
        this.getAxiosData();
    },
    data() {
        return {
            accounts: null,
        }
    },
    methods: {
        /**
         * The CB-ACCESS-SIGN header is generated by creating a sha256 HMAC using the secret
         * key on the prehash string timestamp + method + requestPath + body (where + represents string concatenation).
         *  The timestamp value is the same as the CB-ACCESS-TIMESTAMP header.
         */
        getAxiosData() {

            const apiKey = process.env.VUE_APP_COINBASE_API_KEY;
            const apiSecret = process.env.VUE_APP_COINBASE_API_KEY_SECRET;

            //get unix time in seconds
            var timestamp = Math.floor(Date.now() / 1000);

            var req = {
                method: 'GET',
                path: '/v2/accounts',
                body: ''
            };

            var message = timestamp + req.method + req.path + req.body;
            console.log(message);

            //create a hexedecimal encoded SHA256 signature of the message
            var signature = crypto.createHmac("sha256", apiSecret).update(message).digest("hex");
            axios.create({
                    baseURL: 'https://api.coinbase.com/',
                    headers: {
                        'CB-ACCESS-SIGN': signature,
                        'CB-ACCESS-TIMESTAMP': timestamp,
                        'CB-ACCESS-KEY': apiKey,
                        'CB-VERSION': '2015-07-22'
                    }
                })
                .get('/v2/accounts')
                .then((response) => {
                    var rawAccounts = response.data.data;
                    this.accounts = rawAccounts.filter(account => account.balance.amount != 0)

                }).catch((err) => {
                    this.$emit('errorMsg', err)
                });
        }
    },
    computed: {

    }
}
</script>

<style lang="scss" scoped>
.wallet {}
</style>
